version: "3"
services:
  grafana:
    image: grafana/grafana-oss:8.2.6
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=lightstep-app,grafana-lightstep-datasource,grafana-lightstep-graph
      - GF_LOG_LEVEL=debug
      - GF_DEFAULT_APP_MODE=development
      - LIGHTSTEP_API_KEY=${LIGHTSTEP_API_KEY}
    volumes:
      - grafana-data-lgp:/var/lib/grafana
      - ./:/var/lib/grafana/plugins/grafana-lightstep-app
      - ./provisioning:/etc/grafana/provisioning

volumes:
  grafana-data-lgp:
    external: true